[package]
name = "yew-web3-template"
version = "0.1.0"
edition = "2021"

[dependencies]
web3 = { version = "0.18.0", default-features = false, features = ["http-rustls-tls", "wasm", "eip-1193"] }
wasm-bindgen-futures = "0.4.30"
log = "0.4.17"
wasm-logger = "0.2.0"
yew = "0.19.3"
