[package]
name = "ethereum-provider-simple-example"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.17"
wasm-logger = "0.2.0"
yew = { version = "0.20.0", features=["csr"] }
yew-ethereum-provider = { path = "../.." }
